kind: pipeline
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build

  - name: permissions
    image: alpine:latest
    commands:
      - chmod 777 -R ./dist

  - name: create_pdf
    image: justinribeiro/chrome-headless
    commands:
      - google-chrome --headless --disable-gpu --no-sandbox --disable-setuid-sandbox --print-to-pdf=./dist/Piyush_Kakkar_Resume.pdf ./dist/index.html

  - name: commit-and-push-pdf
    image: docker:git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git fetch
      - git checkout gh-pages
      - mv dist/Piyush_Kakkar_Resume.pdf ./
      - git config user.email "kakkarpiyush96@gmail.com"
      - git config user.name "Piyush Kakkar"
      - git add --all
      - git commit -m "Updating Resume, `date`"
      - git remote add origin-resume https://$GITHUB_TOKEN@github.com/$DRONE_REPO.git > /dev/null 2>&1
      - git push --set-upstream origin-resume gh-pages
    when:
      event:
      - tag
      - promote
      target:
      - build

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/Piyush_Kakkar_Resume.pdf
    when:
      event:
      - tag
