kind: pipeline
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build

  - name: create_pdf
    image: justinribeiro/chrome-headless
    commands:
      - google-chrome --headless --disable-gpu --print-to-pdf=./dist/Piyush_Kakkar_Resume.pdf ./dist/index.html

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/Piyush_Kakkar_Resume.pdf

trigger:
  event: tag
